### PR TITLE
add eth2 check to score calculator

### PR DESCRIPTION
**Pull request by aomerk**

### CODE REVIEW

**Comment by aomerk** [comment]
this safe to merge since `isETH2` input will default to false as long as analyzer doesn't set it to true

**Comment by canercidam** [comment]
Do we need to make another node release for this? I feel like there is another way to do this by just involving the analyzer and maybe we should have probably done it the same way when we added a check for trace support.

The inspection is able to map the list of chain IDs to the feature to be checked, at this line: https://github.com/forta-network/forta-core-go/blob/master/inspect/api.go#L115
Analyzer could do the same thing if it reused the logic. If we:
- move that `==` line to a new exported method down below like `ShouldCheckETH2()`
- use that method in the `SupportsETH2()` method at the same line (L115)
- instead of trying to check input flag, do `inspect.ShouldCheckETH2(results.Indicators[inspect.IndicatorScanAPIChainID])`
- just update `forta-core-go` dependency in analyzer and push when we need

then we could get away without any node updates. Does it make sense? I think I would also move the trace support check logic the same way. Or maybe it's easier to bundle this with a few other improvements and just make a node release.

Also, do we need to check proxy API, too? We seem to check only scan and trace.

Thanks for dealing with this!

**Comment by aomerk** [comment]
@canercidam 
> Do we need to make another node release for this? I feel like there is another way to do this by just involving the analyzer and maybe we should have probably done it the same way when we added a check for trace support.

I don't think it needs a node release because they already submit eth2 indicators, this feels like a calculator-only feature. But, I can see why you thought this pr would imply a node release, since it is using a new inputs field. The reason I've used inputs was that my initial instinct was to use `ScoreCalculatorConfig`, but it looks like we've deprecated using that struct. So I've kept the same clockwork with `CheckTrace`. 

I was thinking about manually setting that input field on the analyzer side, something like this:
```
IsETH2: batch.ChainId is 1 or 5
```

I don't have a preference for which way to go, but I think we need to choose a final way to configure calculations. Because we have:
- calculator config: i guess we don't really use this anymore?
- inspection configs: which we use for calculation configuration
- hardcoded stuff, like `inspect.SupportsETH2()` function

and it feels like it is becoming a bit messier than necessary

**Comment by canercidam** [comment]
I guess I don't have a strong opinion about any of them either.

The only change I would prefer to avoid is the one in [protocol/batch.proto](https://github.com/forta-network/forta-core-go/pull/113/files#diff-980bb5e7412e6004f96bafada9e8c7b56b76677388021677033018c57b6e169f) because it gives an impression that the nodes will start reporting this. It would be a little better if the calculator didn't depend on this definition and rather define something like this if needed:
```
type Inputs struct {
  *protocol.InspectionInputs
  CheckETH2 bool
}
```

**Review by canercidam — APPROVED** [review]

**Pull request merged**
